[theme]
name = "$HOME/Src/i3status-rust/files/themes/solarized-dark.toml"
[icons]
name = "$HOME/Src/i3status-rust/files/icons/awesome.toml"

[[block]]
block = "custom"
command = "i3-msg -t get_tree | jq -r 'recurse(.nodes[];.nodes!=null)|select(.nodes[].focused).layout'"
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
player = "spotify"
max_width = 35
buttons = ["prev", "play", "next"]

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
# format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "xrandr"
icons = true
interval = 2

[[block]]
block = "networkmanager"
on_click = "termite -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
# [block.color_overrides]
# good_bg = "#990000"
# good_fg = "ffffff"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
